[package]
name = "fieldx_derive"
version = "0.1.0"
edition = "2021"
license = "BSD-3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fieldx_derive_support = { workspace = true }
darling = { workspace = true, features = ["suggestions"] }
delegate = { workspace = true }
enum_dispatch = { workspace = true }
getset = { workspace = true }
paste = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
rust-format = { workspace = true }
serde = { workspace = true, optional = true }
syn = { workspace = true, features = ["extra-traits", "parsing"] }
thiserror = { workspace = true }

[lib]
proc-macro = true

[features]
tracing = []
diagnostics = ["darling/diagnostics"]
serde = ["dep:serde"]
