[package]
name = "fieldx_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = { workspace = true }
syn = {workspace = true, features = ["extra-traits", "parsing"] }
# darling = { version = ">=0.20.7", features = ["diagnostics", "suggestions"] }
darling = { workspace = true, features = [ "suggestions"] }
proc-macro2 = { workspace = true }
rust-format = { workspace = true }
enum_dispatch = { workspace = true }
delegate = { workspace = true }
getset = { workspace = true }
thiserror = { workspace = true }
paste = { workspace = true }

[lib]
proc-macro = true

[features]
tracing = []
diagnostics = ["darling/diagnostics"]