unstable_features = true
max_width=120
comment_width=120
control_brace_style="ClosingNextLine"
edition="2021"
enum_discrim_align_threshold=32
format_macro_matchers=true
format_macro_bodies=true
imports_granularity="Item"
normalize_comments=true
reorder_impl_items=true
reorder_imports=true
struct_field_align_threshold=32
