[workspace]
resolver = "2"
members = ["fieldx", "fieldx_derive", "fieldx_derive_support"]

[workspace.dependencies]
fieldx = { version = "0.1.0", path = "fieldx" }
fieldx_derive = { version = "0.1.0", path = "fieldx_derive" }
fieldx_derive_support = { version = "0.1.0", path = "fieldx_derive_support" }
crossbeam = "0.8"
darling = ">=0.20.7"
delegate = "0.12"
enum_dispatch = "0.3"
getset = "0.1"
num_cpus = "1.16"
parking_lot = "0.12"
paste = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
rust-format = "0.3"
# serde = { path = "../serde/serde", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
syn = "2.0"
thiserror = "1.0"
trybuild = "1.0"

[patch.crates-io]
fieldx = { path = "fieldx" }
fieldx_derive = { path = "fieldx_derive" }
fieldx_derive_support = { path = "fieldx_derive_support" }
