[workspace]
resolver = "2"
members = ["fieldx", "fieldx_derive"]

[workspace.dependencies]
fieldx = {version = "0.1.0", workspace = true }
fieldx_derive = { version = "0.1.0", workspace = true }
parking_lot = "0.12"
thiserror = "1.0"
getset = "0.1"
quote = "1.0"
syn = "2.0"
darling = ">=0.20.7"
proc-macro2 = "1.0"
rust-format = "0.3"
enum_dispatch = "0.3"
delegate = "0.12"
paste = "1.0"
trybuild = "1.0"
num_cpus = "1.16"
crossbeam = "0.8"

[patch.crates-io]
fieldx = { path = "fieldx" }
fieldx_derive = { path = "fieldx_derive" }