pre-release-replacements = [
    { file = "src/lib.rs", search = "(doc\\s*\\(html_root_url\\s*=\\s*\"https://docs.rs/.+?)/\\d+\\.\\d+\\.\\d.*/\"", replace = "$1/{{version}}/\"", prerelease = false },
]
