[package]
name = "fieldx"
version = "0.1.0"
edition = "2021"
authors = ["vrurg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fieldx_derive = { workspace = true, features = ["tracing"] }
parking_lot = { workspace = true }
thiserror = { workspace = true }
getset = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
trybuild = { workspace = true }
parking_lot = { workspace = true }
num_cpus = { workspace = true }
crossbeam = { workspace = true }
rustc_version = "0.4"
serde_json = "1.0"

[features]
diagnostics = ["fieldx_derive/diagnostics"]
serde = ["fieldx_derive/serde", "parking_lot/serde", "dep:serde"]
# default = ["serde"]
