[package]
name = "fieldx"
version = "0.1.0"
description = "Procedural macro for constructing structs with lazily initialized fields, builder pattern, and serde support with a focus on declarative syntax."
readme = "../README.md"
edition.workspace = true
license-file.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
category.workspace = true
exclude.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fieldx_derive = { workspace = true, features = ["tracing"] }
parking_lot = { workspace = true }
thiserror = { workspace = true }
getset = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
trybuild = { workspace = true }
parking_lot = { workspace = true }
num_cpus = { workspace = true }
crossbeam = { workspace = true }
serde_json = { workspace = true }
rustc_version = { workspace = true }

[features]
diagnostics = ["fieldx_derive/diagnostics"]
serde = ["fieldx_derive/serde", "parking_lot/serde", "dep:serde"]