[tasks.test-compilation]
    category = "Test"
    description = "Test code compilability"
    script = '''
echo Testing compilability with toolchain '${__FIELDX_DEFAULT_TOOLCHAIN__}'
cm_run_task compile-default-features
cm_run_task compile-serde-enabled
'''
    script_runner = "@duckscript"
    toolchain = "${__FIELDX_DEFAULT_TOOLCHAIN__}"

[tasks.compile-default-features]
    args        = ["test", "--test", "compilation"]
    category    = "Test"
    command     = "cargo"
    description = "Test code compilability with default feature set"
    toolchain   = "${__FIELDX_DEFAULT_TOOLCHAIN__}"

[tasks.compile-serde-enabled]
    args        = ["test", "--test", "compilation", "--features", "serde"]
    category    = "Test"
    command     = "cargo"
    description = "Test code compilability with 'serde' feature"
    toolchain   = "${__FIELDX_DEFAULT_TOOLCHAIN__}"
