[tasks.test-compilation]
description = "Test code compilability"
category = "Test"
toolchain = "${__FIELDX_DEFAULT_TOOLCHAIN__}"
script_runner = "@duckscript"
script = '''
echo Testing compilability with toolchain '${__FIELDX_DEFAULT_TOOLCHAIN__}'
cm_run_task compile-default-features
cm_run_task compile-serde-enabled
'''

[tasks.compile-default-features]
description = "Test code compilability with default feature set"
toolchain = "${__FIELDX_DEFAULT_TOOLCHAIN__}"
category = "Test"
command = "cargo"
args = ["test", "--test", "compilation"]

[tasks.compile-serde-enabled]
description = "Test code compilability with 'serde' feature"
toolchain = "${__FIELDX_DEFAULT_TOOLCHAIN__}"
category = "Test"
command = "cargo"
args = ["test", "--test", "compilation", "--features", "serde"]