pre-release-hook = ['/bin/sh', '-c', '''
if [ "$CARGO_MAKE_TASK" != "publish" -a "$CARGO_MAKE_TASK" != "beta" ]; then
    echo "***ERROR*** Must be released with help of 'cargo make publish' in project workspace dir." 1>&2
    exit 1
else
    pushd $WORKSPACE_ROOT >/dev/null
    export CARGO_RELEASE_VERSION={{version}}
    if ! makers changelog; then
        echo "***ERROR*** Changelog generation failed." 1>&2
        exit 1
    fi
    popd
fi
''']

pre-release-replacements = [
    { file = "src/lib.rs", search = "(doc\\s*\\(html_root_url\\s*=\\s*\"https://docs.rs/.+?)/\\d+\\.\\d+\\.\\d.*/\"", replace = "$1/{{version}}/\"", prerelease = true },
]

enable-all-features = false
enable-features     = ["sync", "async-tokio", "serde", "clonable-lock"]
