name: Deploy The Book
on:
  push:
    tags:
      - book-v0.2.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup rust-analyzer
        run:
          |
          rustup component add rust-analyzer
          rustup component list
      - name: Install mdbook
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbook
            version: '0.4.51'
      - name: Install mdbook-linkcheck
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbook-linkcheck
      - name: Install mdbook-admonish
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbook-admonish
      - name: Install mdbook-keeper
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbook-keeper
      - name: Install mdbook-toc
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbook-toc
      - name: Install mdbookkit
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbookkit
            features: rustdoc-link
      - name: Install mdbook-indexing
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbook-indexing
      - name: Install mdbook-cmdrun
        uses: baptiste0928/cargo-install@v3
        with:
            crate: mdbook-cmdrun
      - name: Build The Book
        run: |
          cd fieldx/docs
          mdbook build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'fieldx/docs/book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4