name: CI

on:
  push:
    branches:
      - main
      - v0.2
  pull_request:
      branches:
        - main
        - v0.2

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  with_features:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        toolchain:
          - 1.78
          - stable
          - nightly
        feature:
          - "\"\""
          - async-tokio
          - async-lock
          - sync
          - serde
          - async-tokio,sync
          - async-lock,sync
          - async-tokio,serde
          - async-lock,serde
          - sync,serde
          - async-tokio,sync,serde
          - async-lock,sync,serde
        exclude:
          - os: windows
            toolchain: nightly
    env:
      __FIELDX_DEFAULT_TOOLCHAIN__: ${{ matrix.toolchain }}
      __FIELDX_NO_UNCOMPILABLE__: ${{ matrix.toolchain == 'beta' && '1' || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Show environment variables
        run: env
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo +${{ matrix.toolchain }} test --verbose --all --features ${{ matrix.feature }}
      - run: cargo +${{ matrix.toolchain }} test --verbose --all --features ${{ matrix.feature }},send_guard
        if: matrix.feature == 'serde'
      - run: cargo +${{ matrix.toolchain }} test --verbose --all --examples --features ${{ matrix.feature }}
      - run: cargo +${{ matrix.toolchain }} test --verbose --all --examples --features ${{ matrix.feature }},send_guard
        if: matrix.feature == 'serde'
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: rustup default nightly
      - run: cargo install cargo-docs-rs
      - run: cargo docs-rs -p fieldx
      - run: cargo docs-rs -p fieldx_aux
      - run: cargo docs-rs -p fieldx_core
      - run: cargo docs-rs -p fieldx_derive

